### ISSUE TITLE
dashboard for Grafana 

### ISSUE THREAD

**Issue by therus000** [GridGain-Demos/ignite-prometheus#3]
good day 
i do all that and i got the metrics on port 9000
thank for this. But i wonder if there is i dashboard for Grafana and Prometheus data source 
or i should build the dashboard from beginig ?

**Comment by sdarlington** [comment]
We don't have any standard dashboards, I'm afraid. The metrics that are interesting varies a lot between clients so it's difficult to share something that works for everyone.
