### ISSUE TITLE
Node 2 metrics

### ISSUE THREAD

**Issue by asarper** [GridGain-Demos/ignite-prometheus#4]
Hello,

I have created ignite-prometheus same configuration. I can receive data for the first node via port 9000, but I cannot receive data from node 2 running on a different server. In node 2, the data appears on the 9001 port via localhost. However,on the node 1 computer. I cannot access the data as node2ip:9001 so I can't access node 2 data on prometheus. I need your help.

NOTE: I can access other prometheus metrics on different node.  ex: windows and postgresql

**Comment by sdarlington** [comment]
The sample project is designed to be run on a single machine.

The exporter is configured to only listen on localhost. If you want it to be visible on another host, remove the first parameter in the constructor in the httpServer bean. If your second node runs on a different machine, you don't need to move it to a different port.

**Comment by asarper** [comment]
sdarlington,
Thank you so much for your help. I can run it now
